/**
 * This class is generated by jOOQ
 */
package jooq.database.tables;


import javax.annotation.Generated;

import jooq.database.Public;
import jooq.database.tables.records.TxninRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Txnin extends TableImpl<TxninRecord> {

	private static final long serialVersionUID = -70395366;

	/**
	 * The reference instance of <code>public.TxnIn</code>
	 */
	public static final Txnin TXNIN = new Txnin();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TxninRecord> getRecordType() {
		return TxninRecord.class;
	}

	/**
	 * The column <code>public.TxnIn.address</code>.
	 */
	public final TableField<TxninRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.TxnIn.txn_id</code>.
	 */
	public final TableField<TxninRecord, Integer> TXN_ID = createField("txn_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.TxnIn</code> table reference
	 */
	public Txnin() {
		this("TxnIn", null);
	}

	/**
	 * Create an aliased <code>public.TxnIn</code> table reference
	 */
	public Txnin(String alias) {
		this(alias, TXNIN);
	}

	private Txnin(String alias, Table<TxninRecord> aliased) {
		this(alias, aliased, null);
	}

	private Txnin(String alias, Table<TxninRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Txnin as(String alias) {
		return new Txnin(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Txnin rename(String name) {
		return new Txnin(name, null);
	}
}
