/**
 * This class is generated by jOOQ
 */
package jooq.database.tables;


import javax.annotation.Generated;

import jooq.database.Public;
import jooq.database.tables.records.TxnoutRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Txnout extends TableImpl<TxnoutRecord> {

	private static final long serialVersionUID = -493938865;

	/**
	 * The reference instance of <code>public.TxnOut</code>
	 */
	public static final Txnout TXNOUT = new Txnout();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TxnoutRecord> getRecordType() {
		return TxnoutRecord.class;
	}

	/**
	 * The column <code>public.TxnOut.address</code>.
	 */
	public final TableField<TxnoutRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.TxnOut.txn_id</code>.
	 */
	public final TableField<TxnoutRecord, Integer> TXN_ID = createField("txn_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.TxnOut</code> table reference
	 */
	public Txnout() {
		this("TxnOut", null);
	}

	/**
	 * Create an aliased <code>public.TxnOut</code> table reference
	 */
	public Txnout(String alias) {
		this(alias, TXNOUT);
	}

	private Txnout(String alias, Table<TxnoutRecord> aliased) {
		this(alias, aliased, null);
	}

	private Txnout(String alias, Table<TxnoutRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Txnout as(String alias) {
		return new Txnout(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Txnout rename(String name) {
		return new Txnout(name, null);
	}
}
