/**
 * This class is generated by jOOQ
 */
package jooq.database.tables.records;


import javax.annotation.Generated;

import jooq.database.tables.Block;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlockRecord extends UpdatableRecordImpl<BlockRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = -2039276831;

	/**
	 * Setter for <code>public.Block.block_id</code>.
	 */
	public void setBlockId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Block.block_id</code>.
	 */
	public Integer getBlockId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.Block.hashMerkleRoot</code>.
	 */
	public void setHashmerkleroot(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Block.hashMerkleRoot</code>.
	 */
	public String getHashmerkleroot() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.Block.txn_counter</code>.
	 */
	public void setTxnCounter(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Block.txn_counter</code>.
	 */
	public Integer getTxnCounter() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Block.BLOCK.BLOCK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Block.BLOCK.HASHMERKLEROOT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Block.BLOCK.TXN_COUNTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getBlockId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getHashmerkleroot();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTxnCounter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlockRecord value1(Integer value) {
		setBlockId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlockRecord value2(String value) {
		setHashmerkleroot(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlockRecord value3(Integer value) {
		setTxnCounter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BlockRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BlockRecord
	 */
	public BlockRecord() {
		super(Block.BLOCK);
	}

	/**
	 * Create a detached, initialised BlockRecord
	 */
	public BlockRecord(Integer blockId, String hashmerkleroot, Integer txnCounter) {
		super(Block.BLOCK);

		setValue(0, blockId);
		setValue(1, hashmerkleroot);
		setValue(2, txnCounter);
	}
}
