/**
 * This class is generated by jOOQ
 */
package jooq.database.tables.records;


import javax.annotation.Generated;

import jooq.database.tables.Txnin;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TxninRecord extends TableRecordImpl<TxninRecord> implements Record2<String, Integer> {

	private static final long serialVersionUID = -317971589;

	/**
	 * Setter for <code>public.TxnIn.address</code>.
	 */
	public void setAddress(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.TxnIn.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.TxnIn.txn_id</code>.
	 */
	public void setTxnId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.TxnIn.txn_id</code>.
	 */
	public Integer getTxnId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Txnin.TXNIN.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Txnin.TXNIN.TXN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTxnId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value1(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value2(Integer value) {
		setTxnId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord values(String value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TxninRecord
	 */
	public TxninRecord() {
		super(Txnin.TXNIN);
	}

	/**
	 * Create a detached, initialised TxninRecord
	 */
	public TxninRecord(String address, Integer txnId) {
		super(Txnin.TXNIN);

		setValue(0, address);
		setValue(1, txnId);
	}
}
