/**
 * This class is generated by jOOQ
 */
package jooq.database.tables.records;


import javax.annotation.Generated;

import jooq.database.tables.Txnin;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TxninRecord extends UpdatableRecordImpl<TxninRecord> implements Record7<Integer, String, Integer, Short, String, Short, Integer> {

	private static final long serialVersionUID = 862857038;

	/**
	 * Setter for <code>public.TxnIn.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.TxnIn.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.TxnIn.hashPrevTxn</code>.
	 */
	public void setHashprevtxn(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.TxnIn.hashPrevTxn</code>.
	 */
	public String getHashprevtxn() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.TxnIn.txnOut_id</code>.
	 */
	public void setTxnoutId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.TxnIn.txnOut_id</code>.
	 */
	public Integer getTxnoutId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.TxnIn.scriptLen</code>.
	 */
	public void setScriptlen(Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.TxnIn.scriptLen</code>.
	 */
	public Short getScriptlen() {
		return (Short) getValue(3);
	}

	/**
	 * Setter for <code>public.TxnIn.scriptSig</code>.
	 */
	public void setScriptsig(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.TxnIn.scriptSig</code>.
	 */
	public String getScriptsig() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.TxnIn.seqNo</code>.
	 */
	public void setSeqno(Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.TxnIn.seqNo</code>.
	 */
	public Short getSeqno() {
		return (Short) getValue(5);
	}

	/**
	 * Setter for <code>public.TxnIn.txn_id</code>.
	 */
	public void setTxnId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.TxnIn.txn_id</code>.
	 */
	public Integer getTxnId() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, Integer, Short, String, Short, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, Integer, Short, String, Short, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Txnin.TXNIN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Txnin.TXNIN.HASHPREVTXN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Txnin.TXNIN.TXNOUT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field4() {
		return Txnin.TXNIN.SCRIPTLEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Txnin.TXNIN.SCRIPTSIG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field6() {
		return Txnin.TXNIN.SEQNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Txnin.TXNIN.TXN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getHashprevtxn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTxnoutId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value4() {
		return getScriptlen();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getScriptsig();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value6() {
		return getSeqno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getTxnId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value2(String value) {
		setHashprevtxn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value3(Integer value) {
		setTxnoutId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value4(Short value) {
		setScriptlen(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value5(String value) {
		setScriptsig(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value6(Short value) {
		setSeqno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord value7(Integer value) {
		setTxnId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxninRecord values(Integer value1, String value2, Integer value3, Short value4, String value5, Short value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TxninRecord
	 */
	public TxninRecord() {
		super(Txnin.TXNIN);
	}

	/**
	 * Create a detached, initialised TxninRecord
	 */
	public TxninRecord(Integer id, String hashprevtxn, Integer txnoutId, Short scriptlen, String scriptsig, Short seqno, Integer txnId) {
		super(Txnin.TXNIN);

		setValue(0, id);
		setValue(1, hashprevtxn);
		setValue(2, txnoutId);
		setValue(3, scriptlen);
		setValue(4, scriptsig);
		setValue(5, seqno);
		setValue(6, txnId);
	}
}
