/**
 * This class is generated by jOOQ
 */
package jooq.database.tables.records;


import javax.annotation.Generated;

import jooq.database.tables.Txnout;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TxnoutRecord extends UpdatableRecordImpl<TxnoutRecord> implements Record5<Integer, Long, Short, String, Integer> {

	private static final long serialVersionUID = -797043744;

	/**
	 * Setter for <code>public.TxnOut.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.TxnOut.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.TxnOut.value</code>.
	 */
	public void setValue(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.TxnOut.value</code>.
	 */
	public Long getValue() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>public.TxnOut.scriptLen</code>.
	 */
	public void setScriptlen(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.TxnOut.scriptLen</code>.
	 */
	public Short getScriptlen() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>public.TxnOut.scriptPubKey</code>.
	 */
	public void setScriptpubkey(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.TxnOut.scriptPubKey</code>.
	 */
	public String getScriptpubkey() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.TxnOut.txn_id</code>.
	 */
	public void setTxnId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.TxnOut.txn_id</code>.
	 */
	public Integer getTxnId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Long, Short, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Long, Short, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Txnout.TXNOUT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Txnout.TXNOUT.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return Txnout.TXNOUT.SCRIPTLEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Txnout.TXNOUT.SCRIPTPUBKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Txnout.TXNOUT.TXN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getScriptlen();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getScriptpubkey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTxnId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value2(Long value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value3(Short value) {
		setScriptlen(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value4(String value) {
		setScriptpubkey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value5(Integer value) {
		setTxnId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord values(Integer value1, Long value2, Short value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TxnoutRecord
	 */
	public TxnoutRecord() {
		super(Txnout.TXNOUT);
	}

	/**
	 * Create a detached, initialised TxnoutRecord
	 */
	public TxnoutRecord(Integer id, Long value, Short scriptlen, String scriptpubkey, Integer txnId) {
		super(Txnout.TXNOUT);

		setValue(0, id);
		setValue(1, value);
		setValue(2, scriptlen);
		setValue(3, scriptpubkey);
		setValue(4, txnId);
	}
}
