/**
 * This class is generated by jOOQ
 */
package jooq.database.tables.records;


import javax.annotation.Generated;

import jooq.database.tables.Txnout;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TxnoutRecord extends TableRecordImpl<TxnoutRecord> implements Record2<String, Integer> {

	private static final long serialVersionUID = 1541039637;

	/**
	 * Setter for <code>public.TxnOut.address</code>.
	 */
	public void setAddress(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.TxnOut.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.TxnOut.txn_id</code>.
	 */
	public void setTxnId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.TxnOut.txn_id</code>.
	 */
	public Integer getTxnId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Txnout.TXNOUT.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Txnout.TXNOUT.TXN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTxnId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value1(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord value2(Integer value) {
		setTxnId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TxnoutRecord values(String value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TxnoutRecord
	 */
	public TxnoutRecord() {
		super(Txnout.TXNOUT);
	}

	/**
	 * Create a detached, initialised TxnoutRecord
	 */
	public TxnoutRecord(String address, Integer txnId) {
		super(Txnout.TXNOUT);

		setValue(0, address);
		setValue(1, txnId);
	}
}
