/**
 * This class is generated by jOOQ
 */
package jooq.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.BlockHeader_id_seq</code>
	 */
	public static final Sequence<Long> BLOCKHEADER_ID_SEQ = new SequenceImpl<Long>("BlockHeader_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.Block_block_id_seq</code>
	 */
	public static final Sequence<Long> BLOCK_BLOCK_ID_SEQ = new SequenceImpl<Long>("Block_block_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.TxnIn_id_seq</code>
	 */
	public static final Sequence<Long> TXNIN_ID_SEQ = new SequenceImpl<Long>("TxnIn_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.TxnIn_txnOut_id_seq</code>
	 */
	public static final Sequence<Long> TXNIN_TXNOUT_ID_SEQ = new SequenceImpl<Long>("TxnIn_txnOut_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.TxnIn_txn_id_seq</code>
	 */
	public static final Sequence<Long> TXNIN_TXN_ID_SEQ = new SequenceImpl<Long>("TxnIn_txn_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.TxnOut_id_seq</code>
	 */
	public static final Sequence<Long> TXNOUT_ID_SEQ = new SequenceImpl<Long>("TxnOut_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.TxnOut_txn_id_seq</code>
	 */
	public static final Sequence<Long> TXNOUT_TXN_ID_SEQ = new SequenceImpl<Long>("TxnOut_txn_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.Txn_block_id_seq</code>
	 */
	public static final Sequence<Long> TXN_BLOCK_ID_SEQ = new SequenceImpl<Long>("Txn_block_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.Txn_txn_id_seq</code>
	 */
	public static final Sequence<Long> TXN_TXN_ID_SEQ = new SequenceImpl<Long>("Txn_txn_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
