/**
 * This class is generated by jOOQ
 */
package jooq.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.BlockHeader_id_seq</code>
	 */
	public static final Sequence<Long> BLOCKHEADER_ID_SEQ = new SequenceImpl<Long>("BlockHeader_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.Block_block_id_seq</code>
	 */
	public static final Sequence<Long> BLOCK_BLOCK_ID_SEQ = new SequenceImpl<Long>("Block_block_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.Txn_id_seq</code>
	 */
	public static final Sequence<Long> TXN_ID_SEQ = new SequenceImpl<Long>("Txn_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
