/**
 * This class is generated by jOOQ
 */
package jooq.database;


import javax.annotation.Generated;

import jooq.database.tables.Block;
import jooq.database.tables.Blockheader;
import jooq.database.tables.Txn;
import jooq.database.tables.Txnin;
import jooq.database.tables.Txnout;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.Block
	 */
	public static final Block BLOCK = jooq.database.tables.Block.BLOCK;

	/**
	 * The table public.BlockHeader
	 */
	public static final Blockheader BLOCKHEADER = jooq.database.tables.Blockheader.BLOCKHEADER;

	/**
	 * The table public.Txn
	 */
	public static final Txn TXN = jooq.database.tables.Txn.TXN;

	/**
	 * The table public.TxnIn
	 */
	public static final Txnin TXNIN = jooq.database.tables.Txnin.TXNIN;

	/**
	 * The table public.TxnOut
	 */
	public static final Txnout TXNOUT = jooq.database.tables.Txnout.TXNOUT;
}
